# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI/CD practice with Maven

on:
  push:
    branches: [ master ]

jobs:
  build-on-ubuntu-and-chrome:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
    - name: Install chrome
      run: chmod +x install-google-chrome.sh
   
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  build-on-windows-and-firefox:

     runs-on: windows-latest

     steps:
     - uses: actions/checkout@v1
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
     - name: Install firefox
       run: chmod +x install-firefox.sh
   
     - name: Build with Maven
       run: mvn -B package --file pom.xml
     - name: run multiple commands
       run: |
        echo what is in this directory?
        ls
        echo is java installed?
        java -version
        
  build-on-macos:
  
     runs-on: macos-12
     
     steps:
     - uses: actions/checkout@v1
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
     - name: Install firefox
       run: chmod +x install-firefox.sh
   
     - name: Build with Maven
       run: mvn -B package --file pom.xml
     - name: run multiple commands
       run: |
        echo what is in this directory?
        ls
        echo is java installed?
        java -version
        echo is gradle installed?
        gradle --version
        echo is git installed?
        git --version
        echo android root
        echo $ANDROID_SDK_ROOT
        echo who am i?
        whoami
        echo env variable
        env
        echo disc fragments
        df
        echo selenium jar
        echo $SELENIUM_JAR_PATH
        echo workspace location
        echo $RUNNER_WORKSPACE
        
     
   
